# creating array in numpy



ONE DIMENSTIONAL ARRAY



In [9]:
import numpy as np

x= np.array([2,3,4,5])
print(x)
x
# print(type(x))

[2 3 4 5]


array([2, 3, 4, 5])

# 2d array

In [13]:
x1=np.array([[2,3,4],[5,6,7]])
print(x1)
print()
print(type(x1)) # class type
print()
print(x1.dtype) # data type

[[2 3 4]
 [5 6 7]]

<class 'numpy.ndarray'>

int32


# fiend daimenstion

In [20]:
a=np.array([2,3,4,5]) # list in passing value
print(a) # disply array
print()
print(type(a)) #type of array
print()
print("data typr: ",a.dtype) # data type
print("dimension: ",a.ndim)# dimenstion fiend

[2 3 4 5]

<class 'numpy.ndarray'>

data typr:  int32
dimension:  1


# fiend daimenstion

In [50]:
 a1=np.array([[2,3,4],[4,5,6],[4,5,3]])
print(a1)
print()
print(type(a))
print()
print("type of type : ",a1.dtype)
print("dimension:",a1.ndim)

[[[2 3 4]
  [4 5 6]
  [4 5 3]]]

<class 'numpy.ndarray'>

type of type :  int32
dimension: 3


# creating multidimension array

In [57]:
arr=np.array([2,3,4],ndmin=10)
 
print(arr)
print(arr.ndim)

[[[[[[[[[[2 3 4]]]]]]]]]]
10


In [59]:
ar=np.array([3,5,7,8,9],ndmin=12)
print(ar)
print()
print("class type:",type(ar))
print()
print("data type:",ar.dtype)
print()
print("dimension:",ar.ndim)

[[[[[[[[[[[[3 5 7 8 9]]]]]]]]]]]]

class type: <class 'numpy.ndarray'>

data type: int32

dimension: 12


In [62]:
ar1=np.array([2,3,4,5],ndmin=5)
print(ar1)
print()
print("type of class",type(ar1))
print()
print("data type:",ar1.dtype)
print()
print("dimension:",ar1.ndim)




[[[[[2 3 4 5]]]]]

type of class <class 'numpy.ndarray'>

data type: int32

dimension: 5


In [64]:
z=np.array([3,4,5],ndmin=3)

print(z)
print()

print(type(z))
print()
print(z.dtype)
print()
print(z.ndim)




[[[3 4 5]]]

<class 'numpy.ndarray'>

int32

3
