In [21]:
import numpy as np

# Searching element

In [23]:
arr=np.array([10,20,30,40])
ar=np.where(arr>20)
print(ar)

(array([2, 3], dtype=int64),)


## Sort element

In [30]:
# ome dimension 
s=np.array([10,20,4,30,50,60])
o=np.sort(s)
print("Sorted array :\n",o)
print()
print("dimension:",o.ndim)

Sorted array :
 [ 4 10 20 30 50 60]

dimension: 1


In [34]:
# Two dimension 
r=([[3,4,5],[6,8,9],[10,20,30]])
t=np.sort(r,axis=1) # acoding to 1 axis array 
print(" acoding to 1 axis array :\n",t)
print()
t1=np.sort(r,axis=0)# acoding to 0 axis array
print("acoding to 0 axis array: \n",t1)

 acoding to 1 axis array :
 [[ 3  4  5]
 [ 6  8  9]
 [10 20 30]]

acoding to 0 axis array: 
 [[ 3  4  5]
 [ 6  8  9]
 [10 20 30]]


## Filter in array

In [41]:
fil=np.array([12,14,56,78,45])
f=[True,False,True,False,False]
 
# new=fil[f]
print(fil[f]) 

[12 56]


In [44]:
fi=np.array([2,3,4])
x=[True,False,True]
print(fi[x])

[2 4]


## Shuffle

In [48]:
sh=np.array([3,4,5,68,23])
sh1=np.random.shuffle(sh)
print(" shuffle : \n",sh)

 shuffle : 
 [23  3 68  4  5]


## uniqe 

In [53]:
uni=np.array([1,1,3,4,5,6,7,8,9,4,3,2])
un=np.unique(uni)
print(un)

[1 2 3 4 5 6 7 8 9]


# Resize and ravel

In [61]:
# resize 
re=([23,4,56,78,9,8])
res=np.resize(re,(2,2))
print("resize array\n",res)
print()
res1=np.sort(res)
print("sort aray\n",res1)


resize array
 [[23  4]
 [56 78]]

sort aray
 [[ 4 23]
 [56 78]]


In [71]:
# ravel
v=np.array([34,5,6,7,84,4])
v1=np.ravel(v)
print(v1)

[34  5  6  7 84  4]


# insert and deletion

In [89]:
# insert
nm=np.array([30,56,54,56,78])
print("before insertion array\n",nm)
print()
se=np.insert(nm,2,45) # first in array of name ,second is index number and last is value(arr,2,45)
print( "after insertion array\n",se)

before insertion array
 [30 56 54 56 78]

after insertion array
 [30 56 45 54 56 78]


In [91]:
# deletion
de=np.array([34,3,45,6,4])
fg=np.delete(de,2) # deletion index 2 n of value
print(fg)

[34  3  6  4]
