In [4]:
import numpy as np


# Copy and view

### Copy 

In [12]:
# one dimensional array 
arr=np.array([2,3,5,6,8]) # original array
print("original array :\n ",arr)
print()
c=arr.copy()
print("copy array :\n ",c) # copy array
print()
print("dimension:",c.ndim) # dimension

original array :
  [2 3 5 6 8]

copy array :
  [2 3 5 6 8]
dimension: 1


In [14]:
# Two dimensional array
ar=np.array([[2,3,4],[12,13,14]])
print(" original array array : \n",ar)
print()
x=ar.copy()
print("copy array : \n",x)
print()
print("dimension:",x.ndim) # dimension

 original array array : 
 [[ 2  3  4]
 [12 13 14]]

copy array : 
 [[ 2  3  4]
 [12 13 14]]

dimension: 2


## View

In [19]:
# one dimension
p=np.array([12,13,15])
print(" original array \n",p)
print()
p1=p.view()
print("view array : \n",p1)
print()
print("dimension : ",p1.ndim)

 original array 
 [12 13 15]

view array : 
 [12 13 15]

dimension :  1


In [21]:
# Two dimensional array
ar1=np.array([[2,3,4],[12,13,14]])
print(" original array array : \n",ar1)
print()
x1=ar1.view()
print("view array : \n",x1)
print()
print("dimension:",x1.ndim) # dimension

 original array array : 
 [[ 2  3  4]
 [12 13 14]]

view array : 
 [[ 2  3  4]
 [12 13 14]]

dimension: 2


### Join array

In [22]:
j=np.array([3,4,5])
l=np.array([10,12,13])
n=np.concatenate((j,l),axis=0)
print(n)

[ 3  4  5 10 12 13]


### Marze

In [35]:
m=np.array([12,15,23,24])
r=np.array([10,20,30,40])
z=np.stack((m,r),axis=0) # acoding to 0 axis
print("acoding to 0 axis",z)
print()
z1=np.stack((m,r),axis=1) # acoding to 1 axis
print("acoding to 1 axis:\n" ,z1)
print()
print("dimension :",z.ndim)

acoding to 0 axis [[12 15 23 24]
 [10 20 30 40]]

acoding to 1 axis:
 [[12 10]
 [15 20]
 [23 30]
 [24 40]]

dimension : 2


### Split array

In [41]:
h=np.array([2,12,23,45,67,45])
h1=np.split(h,3)
print(h1)


[array([ 2, 12]), array([23, 45]), array([67, 45])]
