In [10]:
import numpy as np
 

# Data types in numpy array

## Integers data type

In [13]:
ar=np.array([5,6,7])
print(ar)
print()
print("Data type :",ar.dtype)

[5 6 7]

Data type : int32


### Float data type

In [39]:
arr=np.array([2.3,4.3,5.6])
 
print(arr)
print("Data type : ", arr.dtype)

[2.3 4.3 5.6]
Data type :  float64


In [16]:
 ar1=np.array([True,False,True,True,False])
print(ar1)
print()
print("Data type : ",ar1.dtype)


[ True False  True  True False]

Data type :  bool


# Change data type

In [67]:
p=np.array([4,5,7],dtype="f")# integer to float change 
print(p)


[4. 5. 7.]


# Shape

In [63]:
a=np.array([[5,6],[6,8],[3,6]])
print(a)
print(a.shape) # fiend row and colom
print("Dimension : ",a.ndim)

[[5 6]
 [6 8]
 [3 6]]
(3, 2)
Dimension :  2


In [73]:
m=np.array([[4,7,7],[8,9,6],[5,3,2]])
print(m)
print()
print(m.shape)

[[4 7 7]
 [8 9 6]
 [5 3 2]]

(3, 3)


### Re-shape

In [33]:
import numpy as np

In [61]:
ax=np.array([2,3,4,5,7,8])
y=ax.reshape(3,2) # value enter the row and colom (3 row and 2 colom)
print(y)

[[2 3]
 [4 5]
 [7 8]]


In [68]:
z=np.array([4,6,7,8,9,0])
q=z.reshape(3,2)
print(q)

[[4 6]
 [7 8]
 [9 0]]
