In [4]:
import numpy as np


# Slicing and indexing

### Indexing

In [21]:
arr=np.array([4,5,6,7])
print("Element : ",arr[1]) # index number =1 (indexing start to 0 )
print()
print("Element : ",arr[-3])

Element :  5

Element :  5


In [19]:
ar= np.array([[3,4,5],[6,8,9]]) # two dimension array
print(ar[1,2]) # first value of row and second value of column 

9


### Slicing 

In [34]:
x=np.array([10,40,20,30,50])
print("sliced array:",x[1:4])
print("dimension:",x.ndim)

sliced array: [40 20 30]
dimension: 1


In [33]:
x1=np.array([[3,4,5],[5,8,9]])
print("sliced array:",x1[1:3])
print("dimension:",x1.ndim)

sliced array: [[5 8 9]]
dimension: 2


In [40]:
y=np.array([[3,4,5],[5,8,9],[4,7,9]])
print("sliced array:\n",y[1:3,0:2])
print()
print("dimension:",y.ndim)

sliced array:
 [[5 8]
 [4 7]]

dimension: 2


### Boolean indexing

In [47]:
p=np.array([2,3,5,6,7,9])
print(">3\n",p[p>3]) # element greater than 3 value print
print()
print("<3\n:",p[p<3])
print("dimension :",p.ndim)

>3
 [5 6 7 9]

<3
: [2]
dimension : 1


In [49]:
x=np.array([[4,5,6],[12,13,14],[15,3,10]])
print( "grater than 10 \n",x[x>10])
print()
print("less than 10\n",x[x<10])

grater than 10 
 [12 13 14 15]

less than 10
 [4 5 6 3]
