In [126]:
import numpy as np


# Types of array in numpy

### Zeros array

In [127]:
#import numpy as np
z=np.zeros(3)
print(z)

[0. 0. 0.]


In [128]:
y=np.zeros(9)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [129]:
x=np.zeros((3,4))
print(x)
print()
print("type of class:",type(x))
print()
print("dimension:",x.ndim)
print()
print("data type:",x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

type of class: <class 'numpy.ndarray'>

dimension: 2

data type: float64


In [130]:
x1=np.zeros((3,4,5))
print(z1)
print()
print("type of class:",type(x1))
print()
print("dimension:",x1.ndim)
print()
print("data type:",x1.dtype)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

type of class: <class 'numpy.ndarray'>

dimension: 3

data type: float64


### Ones

In [131]:
v=np.ones(3)
print(v)
print()
print(type(v)) # class type
print()
print(v.dtype) # data of type
print()
print(v.ndim) # dimension

[1. 1. 1.]

<class 'numpy.ndarray'>

float64

1


##### Creat array

In [132]:
v1=np.ones((2,3,4))
print(v1)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


#### Types of class

In [133]:
print(type(v1))

<class 'numpy.ndarray'>


#### Data type

In [134]:
print(v1.dtype)

float64


#### Dimension

In [135]:
print(v1.ndim)

3


## Empty array

In [136]:
n=np.empty(2)
print(n)

[5.43230922e-312 7.29112202e-304]


In [137]:
a=np.empty((3))
print(a)

[7.74860419e-304 7.74860419e-304 7.74860419e-304]


## Range

b=np.arange(3)
print(b)

## digonal array

In [138]:
c=np.eye(4) # 4*4 dignoal matrix

print(c)
print()
print(" Class type : ",type(c))
print()
print("Type of data : ",c.dtype)
print()
print("dimension : ",c.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Class type :  <class 'numpy.ndarray'>

Type of data :  float64

dimension :  2


### 2D dignoal

In [139]:
c1=np.eye(4,2) # 4*2 dignoal matrix

print(c1)
print()
print(" Class type : ",type(c1))
print()
print("Type of data : ",c1.dtype)
print()
print("dimension : ",c1.ndim)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]

 Class type :  <class 'numpy.ndarray'>

Type of data :  float64

dimension :  2


### Line space

In [144]:
d=np.linspace(0,20,num=5)
print(d)

[ 0.  5. 10. 15. 20.]


In [145]:
e=np.linspace(3,9,num=3) # starting point,ending point , how much space
print(e)

[3. 6. 9.]
